# Generated by Django 4.2.27 on 2026-03-24 08:27

from django.db import migrations


def backfill_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Doctor = apps.get_model('accounts', 'Doctor')
    doctor_user_ids = Doctor.objects.values_list('user_id', flat=True)
    User.objects.filter(id__in=doctor_user_ids).update(role='doctor')


def reverse_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='doctor').update(role='patient')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_passwordresetotp'),
    ]

    operations = [
        migrations.RunPython(backfill_roles, reverse_roles),
    ]
