# Generated by Django 5.1.6 on 2026-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_doctor_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, default='English', help_text='Comma-separated list, e.g. "English, Hindi"', max_length=255),
        ),
    ]
