# Generated by Django 5.1.6 on 2026-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_consultation_fee'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_slot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
